# This workflow will build a docker image and publish it to the registry

name: Publish

env:
  IMAGE: "dns-monitor-web"
  PROJECT: "dnsmonitor"
  REGISTRY: 'europe-docker.pkg.dev'

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    environment: Live
    runs-on: ubuntu-24.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v4'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY }}/${{ env.PROJECT }}/containers/${{ env.IMAGE}}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIP }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          token_format: 'access_token'
          access_token_lifetime: '600s' # 10 minutes should be long enough
          create_credentials_file: false
      - uses: 'docker/login-action@v3'
        with:
          registry: ${{ env.REGISTRY }}
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}